import { ProviderDefinition, ProviderId } from "../types/provider";

export const PROVIDER_DEFINITIONS: Record<ProviderId, ProviderDefinition> = {
  nvidia: {
    id: "nvidia",
    label: "NVIDIA NIM (Default)",
    defaultEndpoint: "https://integrate.api.nvidia.com/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "meta/llama-3.3-70b-instruct",
  },
  openai: {
    id: "openai",
    label: "OpenAI",
    defaultEndpoint: "https://api.openai.com/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "gpt-4o-mini",
  },
  anthropic: {
    id: "anthropic",
    label: "Anthropic",
    defaultEndpoint: "https://api.anthropic.com/v1",
    endpointEditable: false,
    adapter: "anthropic",
    needsApiKey: true,
    exampleModel: "claude-sonnet-5",
  },
  gemini: {
    id: "gemini",
    label: "Gemini",
    defaultEndpoint: "https://generativelanguage.googleapis.com/v1beta",
    endpointEditable: false,
    adapter: "gemini",
    needsApiKey: true,
    exampleModel: "gemini-2.0-flash",
  },
  ollama: {
    id: "ollama",
    label: "Ollama",
    defaultEndpoint: "http://localhost:11434/v1",
    endpointEditable: true,
    adapter: "openai",
    needsApiKey: false,
    exampleModel: "llama3.1",
  },
  lmstudio: {
    id: "lmstudio",
    label: "LM Studio",
    defaultEndpoint: "http://localhost:1234/v1",
    endpointEditable: true,
    adapter: "openai",
    needsApiKey: false,
    exampleModel: "local-model",
  },
  openrouter: {
    id: "openrouter",
    label: "OpenRouter",
    defaultEndpoint: "https://openrouter.ai/api/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "openrouter/auto",
  },
  together: {
    id: "together",
    label: "Together AI",
    defaultEndpoint: "https://api.together.xyz/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
  },
  groq: {
    id: "groq",
    label: "Groq",
    defaultEndpoint: "https://api.groq.com/openai/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "llama-3.3-70b-versatile",
  },
  mistral: {
    id: "mistral",
    label: "Mistral",
    defaultEndpoint: "https://api.mistral.ai/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "mistral-large-latest",
  },
  deepseek: {
    id: "deepseek",
    label: "DeepSeek",
    defaultEndpoint: "https://api.deepseek.com/v1",
    endpointEditable: false,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "deepseek-chat",
  },
  "openai-compatible": {
    id: "openai-compatible",
    label: "OpenAI Compatible",
    defaultEndpoint: "",
    endpointEditable: true,
    adapter: "openai",
    needsApiKey: true,
    exampleModel: "your-model-name",
  },
};

export function getProviderDefinition(id: string): ProviderDefinition {
  return PROVIDER_DEFINITIONS[id as ProviderId] ?? PROVIDER_DEFINITIONS.nvidia;
}
